### ISSUE TITLE
Error: Requiring module "node_modules/react-native-chat-uikit/src/containers/GlobalContainer.tsx", which threw an exception: Invariant Violation: `new NativeEventEmitter()` requires a non-null argument. 

### ISSUE THREAD

**Issue by Dwyaneluo** [easemob/react-native-chat-library#1]
### Description

在 iOS 设备上打开报错

### Version

1.0.3

### Output of `npx react-native info`

System:
    OS: macOS 13.2.1
    CPU: (8) x64 Apple M1
    Memory: 29.14 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm
    Watchman: 2023.10.09.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 33, 34
      Build Tools: 28.0.3, 29.0.3, 30.0.2, 30.0.3, 34.0.0
      System Images: android-29 | Android TV Intel x86 Atom, android-29 | ARM 64 v8a, android-29 | Intel x86 Atom, android-29 | Intel x86_64 Atom, android-29 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86_64 Atom, android-29 | Google Play ARM 64 v8a, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86_64 Atom, android-31 | Google TV ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10406996
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.5 => 0.66.5
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

按照文档中的方式集成 在安卓上可以打开聊天页面,在iOS上报错
`import {KeyboardAvoidingView, StyleSheet, Text, View} from 'react-native';
import React from 'react';
import {ChatFragment, ScreenContainer, GlobalContainer as UikitContainer} from 'react-native-chat-uikit';
import {useNavigation, useRoute} from '@react-navigation/native';
import Constants from '../../../constants';
import {NavigationBar} from '../../../kit';

const ChatScreenPage = () => {
    const navigation = useNavigation();
    const route = useRoute<any>();
    const {chatId, chatType, title} = route.params ?? {};

    const onBackPress = () => {
        navigation.goBack();
    };

    return (
        <UikitContainer
            option={{
                appKey: Constants.IMAppKey,
                autoLogin: true,
                debugModel: Constants.DebugMode != '',
            }}>
            <NavigationBar title={title} noLine isLeftShow onLeftClick={onBackPress} />
            <KeyboardAvoidingView behavior={'height'} style={{flex: 1}}>
                <ScreenContainer mode="padding" edges={['right', 'left', 'bottom']}>
                    <ChatFragment screenParams={{params: {chatId, chatType}}} />
                </ScreenContainer>
            </KeyboardAvoidingView>
        </UikitContainer>
    );
};

export default ChatScreenPage;

const styles = StyleSheet.create({});
`

### Snack, code example, screenshot, or link to a repository

![image](https://github.com/easemob/react-native-chat-library/assets/9880518/3a6d057a-7128-438f-84f4-254018c37f0d)
![image](https://github.com/easemob/react-native-chat-library/assets/9880518/17a162e9-6681-4bd2-bda1-d3bb4a87358f)

### Platform

- [ ] All
- [ ] Android
- [X] iOS

### SimulatorOrDevice

- [ ] All
- [ ] Simulator
- [X] Device

### iOSVersion

- [ ] All
- [ ] iOS Earlier than 8
- [ ] iOS 8
- [ ] iOS 9
- [ ] iOS 10
- [ ] iOS 11
- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [X] iOS 16 or above
- [ ] Android Earlier than API Level 23
- [ ] Android API Level 23
- [ ] Android API Level 24
- [ ] Android API Level 25
- [ ] Android API Level 26
- [ ] Android API Level 27
- [ ] Android API Level 28
- [ ] Android API Level 29
- [ ] Android API Level 30
- [ ] Android API Level 31
- [ ] Android API Level 32
- [ ] Android API Level 33 or above

**Comment by AsteriskZuo** [comment]
Version 1.0.3 will no longer be maintained, and version 2.1 is recommended.
